import Breadcrumb from "@/components/Breadcrumb"
import Header from "@/components/Header"
import Sidebar from "@/components/Sidebar"
import { Inter } from "next/font/google"
import Head from "next/head"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Paisen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/favicon.png" />
      </Head>

      <Header />
      <Sidebar currentPage="home" />
      <main id="main" class="main">
        <Breadcrumb name="Home"/>
      </main>
    </>
  )
}
