import { Inter } from "next/font/google"
import Head from "next/head"
import Hero from "../components/Hero"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Paisen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Welcome"
        message="Synchronise your jellyfin anime watch list with myanimelist list. Also, control your mynaimelist account with a unique UI"
      />
    </>
  )
}
