/**
 * Jellyfin Troubleshooting Component
 * 
 * This component provides step-by-step troubleshooting guidance for
 * common Jellyfin connection and configuration issues.
 * 
 * Features:
 * - Common error diagnosis
 * - Step-by-step solutions
 * - Network connectivity checks
 * - Configuration validation tips
 */

import { useState } from 'react'

function JellyfinTroubleshoot() {
  const [expandedSection, setExpandedSection] = useState(null)

  const toggleSection = (section) => {
    setExpandedSection(expandedSection === section ? null : section)
  }

  const troubleshootingSteps = [
    {
      id: 'connection-refused',
      title: 'Connection Refused (ECONNREFUSED)',
      icon: 'bi-x-circle',
      color: 'danger',
      description: 'The most common issue - Jellyfin server is not accessible',
      steps: [
        'Verify Jellyfin server is running and accessible',
        'Check if you can access Jellyfin web interface in your browser',
        'Ensure the server URL is correct (including protocol and port)',
        'If using localhost, make sure Jellyfin is running on the same machine',
        'If using network IP, ensure firewall allows connections on port 8096',
        'Try accessing: http://your-server-ip:8096/web in a browser first'
      ]
    },
    {
      id: 'server-not-found',
      title: 'Server Not Found (ENOTFOUND)',
      icon: 'bi-question-circle',
      color: 'warning',
      description: 'DNS resolution failed - server hostname cannot be resolved',
      steps: [
        'Check if the server hostname/domain is correct',
        'Try using IP address instead of hostname',
        'Verify DNS resolution: ping your-jellyfin-server.com',
        'If using a local domain, check your local DNS/hosts file',
        'Ensure you have internet connectivity if using external domain'
      ]
    },
    {
      id: 'timeout',
      title: 'Connection Timeout (ETIMEDOUT)',
      icon: 'bi-clock',
      color: 'warning',
      description: 'Server is taking too long to respond',
      steps: [
        'Check network connectivity to the server',
        'Verify firewall settings on both client and server',
        'Try increasing timeout in network settings',
        'Check if server is under heavy load',
        'Test with a different network connection'
      ]
    },
    {
      id: 'auth-failed',
      title: 'Authentication Failed (401)',
      icon: 'bi-shield-x',
      color: 'danger',
      description: 'API key is invalid or incorrect',
      steps: [
        'Verify the API key was copied correctly (no extra spaces)',
        'Ensure the API key was generated by an admin user',
        'Check if the API key has been deleted or expired',
        'Try generating a new API key in Jellyfin Dashboard → API Keys',
        'Ensure the API key has proper permissions'
      ]
    },
    {
      id: 'forbidden',
      title: 'Access Forbidden (403)',
      icon: 'bi-shield-exclamation',
      color: 'warning',
      description: 'API key lacks sufficient permissions',
      steps: [
        'Ensure the API key was created by an administrator',
        'Check user permissions in Jellyfin Dashboard → Users',
        'Verify the user account is not disabled',
        'Try creating a new API key with admin privileges'
      ]
    },
    {
      id: 'not-found',
      title: 'API Endpoint Not Found (404)',
      icon: 'bi-search',
      color: 'info',
      description: 'Jellyfin API endpoint is not available',
      steps: [
        'Check Jellyfin server version compatibility',
        'Ensure server URL does not include /web or other paths',
        'Verify Jellyfin server is fully started and initialized',
        'Try accessing /System/Info endpoint manually in browser'
      ]
    }
  ]

  return (
    <div className="card">
      <div className="card-header">
        <h5 className="card-title mb-0">
          <i className="bi bi-tools me-2"></i>
          Troubleshooting Guide
        </h5>
      </div>
      
      <div className="card-body">
        <p className="text-muted mb-3">
          Having connection issues? Click on the error type below for step-by-step solutions.
        </p>

        <div className="accordion" id="troubleshootAccordion">
          {troubleshootingSteps.map((step) => (
            <div key={step.id} className="accordion-item">
              <h2 className="accordion-header">
                <button
                  className={`accordion-button ${expandedSection === step.id ? '' : 'collapsed'}`}
                  type="button"
                  onClick={() => toggleSection(step.id)}
                  aria-expanded={expandedSection === step.id}
                >
                  <i className={`${step.icon} text-${step.color} me-2`}></i>
                  <strong>{step.title}</strong>
                  <span className="ms-2 text-muted">- {step.description}</span>
                </button>
              </h2>
              <div
                className={`accordion-collapse collapse ${expandedSection === step.id ? 'show' : ''}`}
              >
                <div className="accordion-body">
                  <h6>Solution Steps:</h6>
                  <ol>
                    {step.steps.map((stepText, index) => (
                      <li key={index} className="mb-2">
                        {stepText}
                      </li>
                    ))}
                  </ol>
                </div>
              </div>
            </div>
          ))}
        </div>

        <hr className="my-4" />

        <h6>
          <i className="bi bi-lightbulb me-2"></i>
          Quick Checks
        </h6>
        <div className="row">
          <div className="col-md-6">
            <h6 className="text-primary">Before Testing Connection:</h6>
            <ul className="list-unstyled small">
              <li>✓ Jellyfin server is running</li>
              <li>✓ Can access web interface in browser</li>
              <li>✓ API key generated by admin user</li>
              <li>✓ Username exists on server</li>
            </ul>
          </div>
          <div className="col-md-6">
            <h6 className="text-success">URL Format Examples:</h6>
            <ul className="list-unstyled small">
              <li><code>http://localhost:8096</code></li>
              <li><code>http://192.168.1.100:8096</code></li>
              <li><code>https://jellyfin.mydomain.com</code></li>
              <li><code>http://jellyfin.local:8096</code></li>
            </ul>
          </div>
        </div>

        <div className="alert alert-info mt-3">
          <h6 className="alert-heading">
            <i className="bi bi-info-circle me-2"></i>
            Still Having Issues?
          </h6>
          <p className="mb-2">Try these additional steps:</p>
          <ul className="mb-0">
            <li>Check Jellyfin server logs for errors</li>
            <li>Verify network connectivity with <code>ping</code> or <code>telnet</code></li>
            <li>Test API access manually: <code>curl http://your-server:8096/System/Info</code></li>
            <li>Ensure no proxy or VPN is interfering with connections</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

export default JellyfinTroubleshoot 